Feature/add payer address
mercadopago/sdk-dotnet pull request #153
Opened 2022-08-09 21:51 UTC by marianna-meli

Adding attributes in Point of Interaction to Subscriptions.

2022-08-10 11:36 UTC, rhames07 reviewed
Poderia disponibilizar o link do documento que contém as informações de como deveriam ser as estruturas dos payloads por favor?

2022-08-10 11:36 UTC, rhames07 commented on src/MercadoPago/Client/Payment/PaymentPayerAddressRequest.cs
> +        /// Federal unity.
Unit ou unity?

2022-08-10 11:36 UTC, rhames07 commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        using System;
Arrumar formatação.

2022-08-10 11:36 UTC, rhames07 commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +    public class    PaymentTransactionData
Por que foi adicionado esse espaço?

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentPointOfInteractionRequest.cs
> +        public string Type { get; set; }
esta propriedade pode ser nula
```suggestion
        public string? Type { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public PaymentSubscriptionSequenceRequest SubscriptionSequence { get; set; }
```suggestion
        public PaymentSubscriptionSequenceRequest? SubscriptionSequence { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentSubscriptionSequenceRequest.cs
> +        public int Number { get; set; }
```suggestion
        public int? Number { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public string SubscriptionId { get; set; }
```suggestion
        public string? SubscriptionId { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public string PlanId { get; set; }
esta propriedade não existe na API
```
{
    "message": "The name of the following parameters is wrong : [transaction_data.plan_id]",
    "error": "bad_request",
    "status": 400,
    "cause": [
        {
            "code": 8,
            "description": "The name of the parameters is wrong.",
            "data": "09-08-2022T23:20:28UTC;29dab391-eb18-4f0c-a136-c0dcf34583e4 -> Indication: Check the fields in the request body"
        }
    ]
}
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public string InvoiceId { get; set; }
```suggestion
        public string? InvoiceId { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public PaymentInvoicePeriodRequest InvoicePeriod { get; set; }
```suggestion
        public PaymentInvoicePeriodRequest? InvoicePeriod { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentInvoicePeriodRequest.cs
> +        public string Type { get; set; }
```suggestion
        public string? Type { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public PaymentPaymentReferenceRequest PaymentReference { get; set; }
```suggestion
        public PaymentPaymentReferenceRequest? PaymentReference { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public string BillingDate { get; set; }
```suggestion
        public string? BillingDate { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentPaymentReferenceRequest.cs
> +        public string Id { get; set; }
```suggestion
        public string? Id { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentPaymentReferenceRequest.cs
> +        public string Acquirer { get; set; }
```suggestion
        public string? Acquirer { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentInvoicePeriod.cs
> +        public string Type { get; set; }
```suggestion
        public string? Type { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentPayer.cs
> +        public PaymentPayerAddress Address { get; set; }
```suggestion
        public PaymentPayerAddress? Address { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentPayerAddress.cs
> +        public string FederalUnit { get; set; }
```suggestion
        /// <summary>
        /// Neighborhood.
        /// </summary>
        public string? Neighborhood { get; set; }

        /// <summary>
        /// City.
        /// </summary>
        public string? City { get; set; }

        /// <summary>
        /// Federal unity.
        /// </summary>
        public string? FederalUnit { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentPaymentReference.cs
> +        public string Acquirer { get; set; }
```suggestion
        /// <summary>
        /// Period.
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Acquirer.
        /// </summary>
        public string? Acquirer { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentSubscriptionSequence.cs
> +        public int Number { get; set; }
```suggestion
        public int? Number { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public PaymentSubscriptionSequence SubscriptionSequence { get; set; }
```suggestion
        public PaymentSubscriptionSequence? SubscriptionSequence { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string SubscriptionId { get; set; }
```suggestion
        public string? SubscriptionId { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string PlanId { get; set; }
esta propriedade não existe na API
```
{
    "message": "The name of the following parameters is wrong : [transaction_data.plan_id]",
    "error": "bad_request",
    "status": 400,
    "cause": [
        {
            "code": 8,
            "description": "The name of the parameters is wrong.",
            "data": "09-08-2022T23:20:28UTC;29dab391-eb18-4f0c-a136-c0dcf34583e4 -> Indication: Check the fields in the request body"
        }
    ]
}
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string InvoiceId { get; set; }
```suggestion
        public string? InvoiceId { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public PaymentInvoicePeriod InvoicePeriod { get; set; }
```suggestion
        public PaymentInvoicePeriod? InvoicePeriod { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public PaymentPaymentReference PaymentReference { get; set; }
```suggestion
        public PaymentPaymentReference? PaymentReference { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string BillingDate { get; set; }
```suggestion
        public string? BillingDate { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentPayerRequest.cs
> +        public PaymentPayerAddressRequest Address { get; set; }
```suggestion
        public PaymentPayerAddressRequest? Address { get; set; }
```

2022-08-10 13:55 UTC, gdeandradero commented on src/MercadoPago/Client/Payment/PaymentPayerAddressRequest.cs
> +        public string FederalUnit { get; set; }
```suggestion
        /// <summary>
        /// Neighborhood.
        /// </summary>
        public string? Neighborhood { get; set; }

        /// <summary>
        /// City.
        /// </summary>
        public string? City { get; set; }

        /// <summary>
        /// Federal unity.
        /// </summary>
        public string? FederalUnit { get; set; }
```

2022-08-10 14:51 UTC, eltinMeli requested changes

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Client/Payment/PaymentInvoicePeriodRequest.cs
> +        /// Total.
```suggestion
        /// Type.
```

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Client/Payment/PaymentPaymentReferenceRequest.cs
> +        /// Period.
```suggestion
        /// Payment ID reference.
```

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Client/Payment/PaymentPayerAddressRequest.cs
> +        /// Federal unity.
Unit

@marianna-meli está faltando outros campos
zip_code
street_name
street_number

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Client/Payment/PaymentPaymentReferenceRequest.cs
> +        public string Acquirer { get; set; }
Não vi essa informação na documentação

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Resource/Payment/PaymentInvoicePeriod.cs
> +        /// Total.
```suggestion
        /// Type.
```

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Resource/Payment/PaymentPayer.cs
> +        public PaymentPayerAddress Address { get; set; }
Estes valores não retornam na API, não precisa implementar.

2022-08-10 14:51 UTC, eltinMeli commented on src/MercadoPago/Resource/Payment/PaymentPayerAddress.cs
> +    public class PaymentPayerAddress : Address
Pode deletar essa classe

2022-08-10 19:13 UTC, marianna-meli commented on src/MercadoPago/Client/Payment/PaymentPayerAddressRequest.cs
> +        /// Federal unity.
Nesse caso, o Rhames havia comentado que poderia herdar esses campos da classe Address (src/MercadoPago/Resource/Common/Address.cs) porque já estão implementados... E está sendo declarado na linha 8.

Devo manter a herança ou criar esses outros campos?

2022-08-11 14:38 UTC, marianna-meli commented on src/MercadoPago/Client/Payment/PaymentPaymentReferenceRequest.cs
> +        public string Acquirer { get; set; }
Está na pág 03 dessa [documentação](https://docs.google.com/document/d/1MHHOju3mKm4_8ZCvaVnn5FES6s6UVqfFllyUdB-qKHw/edit#) que passaram para o Romero. Devo manter ou retirar?

2022-08-11 14:40 UTC, marianna-meli commented
> Poderia disponibilizar o link do documento que contém as informações de como deveriam ser as estruturas dos payloads por favor?

Material de apoio:

https://docs.google.com/document/d/1tDEEZGPb5A8uO3rtbIj1Pv23TY24b9qfvL9J0JE4dhM/edit 

https://docs.google.com/document/d/1MHHOju3mKm4_8ZCvaVnn5FES6s6UVqfFllyUdB-qKHw/edit#heading=h.o0p0j4jp1ise

2022-08-11 15:20 UTC, marianna-meli commented on src/MercadoPago/Client/Payment/PaymentPointOfInteractionRequest.cs
> +        public string Type { get; set; }
Conversei com o Danilo, e realmente era o que a IDE estava retornando de erro mesmo. Antes da versão 8.0 do C#, só pode ser usado o nullable em tipos primitivos. Logo, a string pode ser nula, mas não temos como setar isso na declaração da propriedade.

2022-08-11 15:23 UTC, marianna-meli commented on src/MercadoPago/Client/Payment/PaymentSubscriptionSequenceRequest.cs
> +        public int Number { get; set; }
Na documentação essa propriedade não consta que pode ser nullable.

2022-08-11 15:36 UTC, marianna-meli commented on src/MercadoPago/Client/Payment/PaymentTransactionDataRequest.cs
> +        public string PlanId { get; set; }
Conversei com o Eltin e retirei essa propriedade, pois só é utilizada internamente.

2022-08-11 15:38 UTC, marianna-meli commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string InvoiceId { get; set; }
Conversei com o Eltin e retirei essa propriedade pois é utilizada apenas internamente.

2022-08-11 15:39 UTC, marianna-meli commented on src/MercadoPago/Resource/Payment/PaymentTransactionData.cs
> +        public string PlanId { get; set; }
Conversei com o Eltin e retirei essa propriedade pois é utilizada apenas internamente.

2022-08-11 15:48 UTC, gdeandradero approved these changes

2022-08-16 17:46 UTC, eltinMeli approved these changes

2022-08-16 17:59 UTC, merged